services:
  bds:
    image: ghcr.io/djstompzone/bds-pterodactyl
    environment:
      EULA: "TRUE"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
